### ISSUE TITLE
Install on Windows has errors

### ISSUE THREAD

**Issue by WillAdams** [leon-thomm/ryven-blender#1]
Trying this in Blender 3.0.

Running __init__.py doesn't seem to work:

![image](https://user-images.githubusercontent.com/3543154/150134549-265752c7-1d50-4848-94ca-5cc9fcbc619c.png)

**Comment by leon-thomm** [comment]
the error says it cannot find the ryven package. reasons for this might be an unsuccessful installation, or you didn't restart Blender after installing. I've initially had many rather unpredictable issues with Blender's python installation so you might need to follow the README instructions quite precisely

**Comment by WillAdams** [comment]
I followed them to the best of my ability, and have restarted Blender, and each step seemed to complete successfully until the last --- how do I verify that each step was completed correctly?

**Comment by leon-thomm** [comment]
sorry if this feels frustrating, it shouldn't be, Blender's Python integration is really not that great. To verify, check whether blender's python lists ryven as installed package, so let `<BPP>` be the path of your Blender's python executable, run `<BPP> -m pip list` and it should also list `ryven`. If it does, start Blender's Python (simply run `<BPP>`) and try to `import ryven`. When this works, you can try to start Ryven
```python
import ryven
ryven.run_ryven()
```

**Comment by WillAdams** [comment]
When I do that I get:
```
PySide2/__init__.py: Unable to import shiboken2 from , C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin\python39.zip, C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\DLLs, C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib, C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin, C:\Users\willa\AppData\Roaming\Python\Python39\site-packages, C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\win32, C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\win32\lib, C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\Pythonwin, C:\Program Files\Blender Foundation\Blender 3.0\3.0\python, C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages
C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\qtpy\__init__.py:201: RuntimeWarning: Selected binding "pyside2" could not be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\ryven\main\Ryven.py", line 26, in run
    init_node_env()
  File "C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\ryven\NENV.py", line 26, in init_node_env
    from ryvencore_qt import \
  File "C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\ryvencore_qt\__init__.py", line 11, in <module>
    from .src.core_wrapper import *
  File "C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\ryvencore_qt\src\core_wrapper\__init__.py", line 7, in <module>
    from .Node import Node
  File "C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\ryvencore_qt\src\core_wrapper\Node.py", line 1, in <module>
    from qtpy.QtCore import QObject, Signal
  File "C:\Users\willa\AppData\Roaming\Python\Python39\site-packages\qtpy\QtCore.py", line 42, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'
```
I now get:

![image](https://user-images.githubusercontent.com/3543154/151907589-76c3fd2f-7413-4cdd-b0c2-c8bf5ff81af1.png)

in Blender

**Comment by leon-thomm** [comment]
that's strange... qtpy seems to import PyQt5 instead of PySide2, which could also be caused by blender (I wouldn't be surprised). could you run this in Blender and see what it prints?
```python
import os
os.environ['QT_API'] = 'pyside2'
from qtpy.QtCore import QObject, Signal
```

**Comment by WillAdams** [comment]
Running that resulted in:

    Traceback (most recent call last):
      File "<blender_console>", line 1, in <module>
    ModuleNotFoundError: No module named 'qtpy'

**Comment by leon-thomm** [comment]
well, then your `<BPP> -m pip install ryven` may still have used the system-wide pip installation, instead of Blender's Python's pip or something (I've seen both scenarios recently)... hard to tell how to fix that, but that's Blender issues, it probably doesn't have to do anything with ryven or qtpy packages, so I suggest getting help from the blender community...

**Comment by WillAdams** [comment]
Thanks. If the current attempt to install Ryven and PythonOCC doesn't pan out, I'm going to try removing everything and concentrating on the Blender end of things.
